Updated for new trashmail-client version

diff --git a/start b/start
--- a/start
+++ b/start
@@ -5,9 +5,9 @@ DO_SHUTDOWN=1
 
 which curl || exit 1
 
-#for i in lmtp-server trashmail-client; do
-#  docker-compose build --no-cache "$i"
-#done
+for i in lmtp-server trashmail-client; do
+  docker-compose build --no-cache "$i"
+done
 
 if [ -z "$service" ]; then
   docker-compose up -d --no-deps --force-recreate $service || exit 1
@@ -23,6 +23,7 @@ while : ; do
   let count=${count}-1
   if [ $count -eq 0 ]; then exit 1; fi
 done
+echo "lmtp-server ready for service"
 
 count=30
 while : ; do
@@ -32,13 +33,25 @@ while : ; do
   let count=${count}-1
   if [ $count -eq 0 ]; then exit 1; fi
 done
+echo "selenium firefox ready for service"
 
+count=30
+while : ; do
+  docker-compose ps trashmail-client | grep healthy
+  if [ $? -eq 0 ]; then break; fi
+  sleep 1
+  let count=${count}-1
+  if [ $count -eq 0 ]; then exit 1; fi
+done
+echo "trashmail-client (test subject) ready for service"
+
+ECHO=echo
 docker-compose up tester
 if [ $? -eq 0 ]; then
-  echo "success"
+  $ECHO "success"
   res=0
 else
-  echo "failed"
+  $ECHO "failed"
   res=1
 fi
 
