First working version

diff --git a/start b/start
--- a/start
+++ b/start
@@ -1,10 +1,32 @@
 #!/bin/sh
 
 service="$1"
+DO_SHUTDOWN=1
 
 if [ -z "$service" ]; then
   docker-compose up --detach --no-deps --force-recreate $service
 else
-  docker-compose up --detach --force-recreate
+  docker-compose up --detach --scale tester=0
+fi
+
+while : ; do
+  docker-compose ps lmtp-server | grep healthy
+  if [ $? -eq 0 ]; then break; fi
+done
+
+while : ; do
+  docker-compose ps firefox | grep healthy
+  if [ $? -eq 0 ]; then break; fi
+done
+
+docker-compose up tester
+if [ $? -eq 0 ]; then
+  echo "success"
+else
+  echo "failed"
+fi
+
+if [ $DO_SHUTDOWN -eq 1 ]; then
+  docker-compose down
 fi
 
